"""Per-image undo / redo history for the editing operations the user
performs in the GUI (bbox edits, translation edits, text moves, mask
paints, free-form text inserts, and pipeline phase runs).

Snapshots are stored in memory only and reset whenever the user opens
a different image — there's no on-disk format, so reopening a saved
file gives you a clean history rooted at the persisted state.

Design:

* The "current" state is the top of the undo stack.
* :meth:`HistoryManager.record` is called *after* each mutation; it
  pushes the new state and clears the redo stack (any branch that the
  user had stepped through with redo is now lost).
* :meth:`HistoryManager.undo` moves the current state to the redo
  stack and re-applies the previous state to the live PageContext.
* Each :class:`HistoryEntry` deep-copies bboxes / ocr / translations
  so undo / redo reads are independent of subsequent edits. Bbox
  identity (used by ``is`` comparisons elsewhere) is preserved within
  a single entry's lists thanks to a single :func:`copy.deepcopy`
  call that resolves shared references via its memo.
"""
from __future__ import annotations

import copy
import time
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from .models import PageContext


# Snapshots beyond this count are dropped from the bottom of the undo
# stack. 50 lets the user undo through a long editing session without
# unbounded memory growth on per-bbox masks.
MAX_HISTORY = 50


@dataclass
class HistoryEntry:
    """Immutable snapshot of the document-state subset that user edits
    can change.

    ``mask`` and ``cleaned`` / ``final`` are intentionally NOT snapshot
    here — masks only change via a full Detect re-run (out of the edit
    scope) and the cleaned / final images are derived from the other
    fields, regenerated by Step 5.
    """

    label: str
    timestamp: float = field(default_factory=time.time)
    bboxes: list = field(default_factory=list)
    ocr: list = field(default_factory=list)
    translations: list = field(default_factory=list)

    @classmethod
    def from_context(cls, ctx: "PageContext", label: str) -> "HistoryEntry":
        # Deep-copy as one bundle so cross-references between the lists
        # (TranslationResult.bbox is a member of bboxes) survive.
        snap = copy.deepcopy(
            {
                "bboxes": ctx.bboxes,
                "ocr": ctx.ocr,
                "translations": ctx.translations,
            }
        )
        return cls(
            label=label,
            bboxes=snap["bboxes"],
            ocr=snap["ocr"],
            translations=snap["translations"],
        )

    def apply_to(self, ctx: "PageContext") -> None:
        """Replace ``ctx`` editing fields with this snapshot.

        We re-deepcopy on read so multiple round trips through
        undo / redo don't end up sharing aliased lists.
        """
        snap = copy.deepcopy(
            {
                "bboxes": self.bboxes,
                "ocr": self.ocr,
                "translations": self.translations,
            }
        )
        ctx.bboxes = snap["bboxes"]
        ctx.ocr = snap["ocr"]
        ctx.translations = snap["translations"]
        # Derived fields are stale w.r.t. the restored bboxes / texts.
        ctx.cleaned = None
        ctx.final = None


class HistoryManager:
    def __init__(self, max_history: int = MAX_HISTORY):
        self._undo: list[HistoryEntry] = []
        self._redo: list[HistoryEntry] = []
        self._max = max_history

    # ---- mutation ----

    def reset(self, ctx: "PageContext", label: str = "loaded") -> None:
        """Drop all history and seed with ``ctx`` as the floor state."""
        self._undo.clear()
        self._redo.clear()
        self._undo.append(HistoryEntry.from_context(ctx, label))

    def record(self, ctx: "PageContext", label: str) -> None:
        """Snapshot ``ctx`` after a user edit. Clears the redo stack."""
        entry = HistoryEntry.from_context(ctx, label)
        # Skip no-op records (label changed but the data is identical).
        # This keeps spurious records from things like double-applied
        # signal handlers from cluttering the history view.
        if self._undo and self._snapshot_equals(self._undo[-1], entry):
            return
        self._undo.append(entry)
        if len(self._undo) > self._max:
            # Drop the oldest entry — we lose the ability to undo all the
            # way back to "loaded" but that's the trade-off for a bounded
            # in-memory history.
            self._undo.pop(0)
        self._redo.clear()

    # ---- queries ----

    def can_undo(self) -> bool:
        # Need at least two entries: current + a previous one to fall back to.
        return len(self._undo) >= 2

    def can_redo(self) -> bool:
        return bool(self._redo)

    @property
    def current_index(self) -> int:
        """0-based index of the current state inside :meth:`entries`."""
        return len(self._undo) - 1

    def entries(self) -> list[HistoryEntry]:
        """All snapshots oldest → newest. The current state is the last one."""
        return list(self._undo)

    def redo_entries(self) -> list[HistoryEntry]:
        """Snapshots reachable via redo (most-recent-first internally,
        flipped here so the dock shows them in chronological order
        appended to the undo timeline)."""
        return list(reversed(self._redo))

    # ---- undo / redo ----

    def undo(self, ctx: "PageContext") -> Optional[HistoryEntry]:
        if not self.can_undo():
            return None
        current = self._undo.pop()
        self._redo.append(current)
        prev = self._undo[-1]
        prev.apply_to(ctx)
        return prev

    def redo(self, ctx: "PageContext") -> Optional[HistoryEntry]:
        if not self.can_redo():
            return None
        target = self._redo.pop()
        self._undo.append(target)
        target.apply_to(ctx)
        return target

    # ---- internals ----

    @staticmethod
    def _snapshot_equals(a: HistoryEntry, b: HistoryEntry) -> bool:
        """Cheap structural comparison so back-to-back identical records
        are de-duped. ``label`` and ``timestamp`` are ignored."""
        if len(a.bboxes) != len(b.bboxes):
            return False
        if len(a.translations) != len(b.translations):
            return False
        if len(a.ocr) != len(b.ocr):
            return False
        for ba, bb in zip(a.bboxes, b.bboxes):
            if (ba.x, ba.y, ba.w, ba.h) != (bb.x, bb.y, bb.w, bb.h):
                return False
        for ta, tb in zip(a.translations, b.translations):
            # Compare the user-visible attributes only; per-bbox mask
            # array equality is handled separately because numpy arrays
            # don't support direct comparison in a boolean context.
            if (ta.text_ja, ta.text_ko, ta.text_offset_x, ta.text_offset_y,
                    ta.text_align, ta.text_rotation, ta.font_path, ta.font_pt,
                    ta.fill_rgb, ta.stroke_rgb,
                    ta.bg_fill_enabled, ta.bg_fill_rgb, ta.bg_fill_pad) != (
                    tb.text_ja, tb.text_ko, tb.text_offset_x, tb.text_offset_y,
                    tb.text_align, tb.text_rotation, tb.font_path, tb.font_pt,
                    tb.fill_rgb, tb.stroke_rgb,
                    tb.bg_fill_enabled, tb.bg_fill_rgb, tb.bg_fill_pad):
                return False
            # Mask equality
            am = ta.bbox_mask
            bm = tb.bbox_mask
            if (am is None) != (bm is None):
                return False
            if am is not None and bm is not None:
                if am.shape != bm.shape:
                    return False
                # bool() works because we collapse with .all()
                import numpy as np

                if not np.array_equal(am, bm):
                    return False
        for oa, ob in zip(a.ocr, b.ocr):
            if oa.text_ja != ob.text_ja:
                return False
        return True
